title: Markdown in Just the Docs 
description: Exercises in Just the docs
theme: just-the-docs

url: https://krzemionka.github.io/JustThe Docs

aux_links:
  Template Repository: https://github.com/krzemionka/jJustThe Docs
